config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :ingredient, uniqueness: { scope: :cocktail,
    message: "should be a unique pair" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  before_destroy { self.doses }
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render 'new'
    end
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  private

  def cocktails_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  def create
    @dose = Dose.new(doses_params)
    @dose.cocktail = Cocktail.find(@dose.cocktail_id)
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render 'new'
    end
  end

  def new
    @cocktail = Cocktail.find(doses_params[:cocktail_id])
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  private

  def doses_params
    params.require(:dose).permit(:cocktail_id, :ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<h1>add a new cocktail</h1>
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.input_field :name %>
  <%= f.submit 'Save' %>
<% end %>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="add-cocktail">
    <button><%= link_to "Add Cocktail", new_cocktail_path %></button>
  </div>
  <h2>Cocktails</h2>
  <% @cocktails.each do |cocktail| %>
  <div class="card text-center">
    <hr>
    <h1><%= link_to cocktail.name, cocktail %></h1>

  </div>
  <% end  %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="card">
    <h1><%= @cocktail.name %></h1>
    <% @cocktail.doses.each do |dose| %>
    <p>Ingredient: <%= dose.ingredient.name %></p>
    <p>Description: <%= dose.description %></p>
    <%end%>
  </div>
  <div class="add-dose">
    <button><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail.id) %></button>
  </div>

</div>

app/views/doses/_form.html.erb
<h1>add a new dose</h1>
<ul></ul>
<%= simple_form_for @dose , url: cocktail_doses_path do |f| %>
  <%= f.association :ingredient %>
  <%= f.label :description %>
  <%= f.input_field :description %>
  <%= f.input_field :cocktail_id, as: :hidden, input_html: {value: @dose.cocktail_id}%>
  <%= f.submit 'Save' %>
<% end %>

app/views/doses/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <button><%= link_to "Home", cocktails_path %></button>
    <%= yield %>
  </body>
</html>